#pluginGroup=com.floatbar
#pluginName=FloatBar
#pluginVersion=0.1.0
#pluginSinceBuild=233
#pluginUntilBuild=243.*
#pluginSinceBuild=252
#pluginUntilBuild=252.*
#pluginSinceBuild=252
#pluginUntilBuild=253.*

# IntelliJ Platform — PyCharm Community 2023.3.4
#platformType=PC
#platformVersion=2023.3.4

# Java
#javaVersion=17

# Gradle IntelliJ Plugin
#gradleIntelliJPluginVersion=1.17.3


pluginGroup=com.floatbar
pluginName=FloatBar
pluginVersion=0.1.0

pluginSinceBuild=253
pluginUntilBuild=253.*

platformType=IU
platformVersion=2025.3.3

javaVersion=21

kotlin.stdlib.default.dependency=false


#This is a teste to GIT
